### ISSUE TITLE
🎯 Todo 

### ISSUE THREAD

**Issue by trulysaroj** [trulysaroj/Multideal#1]
- [x] Resolved server-side issues
- [x] Create login/Register form
- [x] Design workflow/diagram & flowchart

**Comment by trulysaroj** [comment]
**Note:**
If you encounter issue while connecting MongoDB  with server and show error message like this
`mongooseserverselectionerror connect econnrefused`

In DBconfig JSON file include URI like this
```
{
    "MONGODB_CONNECTION_URI": "mongodb://127.0.0.1:27017" 
}
```

instead of 
```
{
    "MONGODB_CONNECTION_URI": "mongodb://localhost:27017" 
    
}
```

_( In "mongodb://127.0.0.1:27017"  --> 127.0.0.1 is basically it's IP address.
This problem occures only in latest node version or above 16 you can also use older node version to avoid this error)_

**Comment by trulysaroj** [comment]
Today's task is done ...
